language: scala
scala:
  - 2.9.3
  - 2.10.4
  - 2.11.2
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
env:
  - PROJECT_DIR=example
script:
  - cd $PROJECT_DIR && sbt clean test
after_success:
  - bash <(curl -s https://codecov.io/bash)

