language: scala
scala:
#  - 2.9.3
#  - 2.10.6
  - 2.11.8
jdk:
#  - oraclejdk8
#  - oraclejdk7
  - openjdk7
env:
  - PROJECT_DIR=example
  - PROJECT_DIR=week1
  - PROJECT_DIR=week2
  - PROJECT_DIR=week3
script:
  - cd $PROJECT_DIR && sbt clean test
after_success:
  - bash <(curl -s https://codecov.io/bash)

